### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by JarrodCTaylor** [igrishaev/etaoin#35]
An empty Firefox browser window opens and then the test fails immediately.

Firefox version: 54.0.1
OS version: macOS Sierra 10.12.5 

```

Testing etaoin.api-test
DEBUG etaoin.client: firefox 127.0.0.1:4444   POST session {:desiredCapabilities {}}
DEBUG etaoin.client: firefox 127.0.0.1:4444   POST session//url {:url "file:/Users/Jrock/Projects/etaoin/resources/html/test.html"}
DEBUG etaoin.client: firefox 127.0.0.1:4444 DELETE session/ 
Exception in thread "main" clojure.lang.ExceptionInfo: throw+: {:response {:value {:error "unknown command", :message "DELETE /session/ did not match a known command", :stacktrace "stack backtrace:\n   0:        0x103fe3444 - backtrace::backtrace::trace::h9f8fad52a1a8acf1\n   1:        0x103fe37fe - backtrace::capture::Backtrace::new::hbc1a12654c8fdba8\n   2:        0x103f0df4d - webdriver::error::WebDriverError::new::h10bc8992bd1e5ce5\n   3:        0x103eb690d - _$LT$webdriver..httpapi..WebDriverHttpApi$LT$U$GT$$GT$::decode_request::h59625e2271927f5c\n   4:        0x103ef545e - _$LT$webdriver..server..HttpHandler$LT$U$GT$$u20$as$u20$hyper..server..Handler$GT$::handle::h75bcf4a70da4d3d8\n   5:        0x103e35b11 - _$LT$hyper..server..Worker$LT$H$GT$$GT$::keep_alive_loop::h6cffe26f2f997d81\n   6:        0x103e36665 - _$LT$hyper..server..Worker$LT$H$GT$$GT$::handle_connection::ha65f143767ef2701\n   7:        0x103ec24c1 - hyper::server::handle::_$u7b$$u7b$closure$u7d$$u7d$::h021c4837b0330036\n   8:        0x103ec2a5e - hyper::server::listener::spawn_with::_$u7b$$u7b$closure$u7d$$u7d$::h922fff03b485de70\n   9:        0x103f030a7 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hb095877d82356444\n  10:        0x103e47c86 - std::panicking::try::do_call::h7a395bca958e623c\n  11:        0x10447554a - __rust_maybe_catch_panic\n  12:        0x103e475bc - std::panicking::try::h55d8916b3f7a3515\n  13:        0x103e44e52 - std::panic::catch_unwind::hf1717d8b89ed66e7\n  14:        0x103e46ffc - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hd9c5bf9811bb3b73\n  15:        0x103ea1a4c - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h0c4aa35835be38e8\n  16:        0x104471714 - std::sys::imp::thread::Thread::new::thread_start::hae18fa578e305215\n  17:     0x7fffb9b5693a - _pthread_body\n  18:     0x7fffb9b56886 - _pthread_start"}}, :path "session/", :payload nil, :method :delete, :type :etaoin/http-error, :port 4444, :host "127.0.0.1", :status 404, :driver {:args ["geckodriver" "--port" 4444], :desired-capabilities nil, :process #object[java.lang.UNIXProcess 0x5b2ade46 "java.lang.UNIXProcess@5b2ade46"], :locator "xpath", :type :firefox, :env {}, :port 4444, :host "127.0.0.1", :url "http://127.0.0.1:4444", :session nil}} {:response {:value {:error "unknown command", :message "DELETE /session/ did not match a known command", :stacktrace "stack backtrace:\n   0:        0x103fe3444 - backtrace::backtrace::trace::h9f8fad52a1a8acf1\n   1:        0x103fe37fe - backtrace::capture::Backtrace::new::hbc1a12654c8fdba8\n   2:        0x103f0df4d - webdriver::error::WebDriverError::new::h10bc8992bd1e5ce5\n   3:        0x103eb690d - _$LT$webdriver..httpapi..WebDriverHttpApi$LT$U$GT$$GT$::decode_request::h59625e2271927f5c\n   4:        0x103ef545e - _$LT$webdriver..server..HttpHandler$LT$U$GT$$u20$as$u20$hyper..server..Handler$GT$::handle::h75bcf4a70da4d3d8\n   5:        0x103e35b11 - _$LT$hyper..server..Worker$LT$H$GT$$GT$::keep_alive_loop::h6cffe26f2f997d81\n   6:        0x103e36665 - _$LT$hyper..server..Worker$LT$H$GT$$GT$::handle_connection::ha65f143767ef2701\n   7:        0x103ec24c1 - hyper::server::handle::_$u7b$$u7b$closure$u7d$$u7d$::h021c4837b0330036\n   8:        0x103ec2a5e - hyper::server::listener::spawn_with::_$u7b$$u7b$closure$u7d$$u7d$::h922fff03b485de70\n   9:        0x103f030a7 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hb095877d82356444\n  10:        0x103e47c86 - std::panicking::try::do_call::h7a395bca958e623c\n  11:        0x10447554a - __rust_maybe_catch_panic\n  12:        0x103e475bc - std::panicking::try::h55d8916b3f7a3515\n  13:        0x103e44e52 - std::panic::catch_unwind::hf1717d8b89ed66e7\n  14:        0x103e46ffc - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hd9c5bf9811bb3b73\n  15:        0x103ea1a4c - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h0c4aa35835be38e8\n  16:        0x104471714 - std::sys::imp::thread::Thread::new::thread_start::hae18fa578e305215\n  17:     0x7fffb9b5693a - _pthread_body\n  18:     0x7fffb9b56886 - _pthread_start"}}, :path "session/", :payload nil, :method :delete, :type :etaoin/http-error, :port 4444, :host "127.0.0.1", :status 404, :driver {:args ["geckodriver" "--port" 4444], :desired-capabilities nil, :process #object[java.lang.UNIXProcess 0x5b2ade46 "java.lang.UNIXProcess@5b2ade46"], :locator "xpath", :type :firefox, :env {}, :port 4444, :host "127.0.0.1", :url "http://127.0.0.1:4444", :session nil}}, compiling:(/private/var/folders/yp/46_n05bs7k18jnxtkvjfzpk40000gn/T/form-init1325635718044467402.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: throw+: {:response {:value {:error "unknown command", :message "DELETE /session/ did not match a known command", :stacktrace "stack backtrace:\n   0:        0x103fe3444 - backtrace::backtrace::trace::h9f8fad52a1a8acf1\n   1:        0x103fe37fe - backtrace::capture::Backtrace::new::hbc1a12654c8fdba8\n   2:        0x103f0df4d - webdriver::error::WebDriverError::new::h10bc8992bd1e5ce5\n   3:        0x103eb690d - _$LT$webdriver..httpapi..WebDriverHttpApi$LT$U$GT$$GT$::decode_request::h59625e2271927f5c\n   4:        0x103ef545e - _$LT$webdriver..server..HttpHandler$LT$U$GT$$u20$as$u20$hyper..server..Handler$GT$::handle::h75bcf4a70da4d3d8\n   5:        0x103e35b11 - _$LT$hyper..server..Worker$LT$H$GT$$GT$::keep_alive_loop::h6cffe26f2f997d81\n   6:        0x103e36665 - _$LT$hyper..server..Worker$LT$H$GT$$GT$::handle_connection::ha65f143767ef2701\n   7:        0x103ec24c1 - hyper::server::handle::_$u7b$$u7b$closure$u7d$$u7d$::h021c4837b0330036\n   8:        0x103ec2a5e - hyper::server::listener::spawn_with::_$u7b$$u7b$closure$u7d$$u7d$::h922fff03b485de70\n   9:        0x103f030a7 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hb095877d82356444\n  10:        0x103e47c86 - std::panicking::try::do_call::h7a395bca958e623c\n  11:        0x10447554a - __rust_maybe_catch_panic\n  12:        0x103e475bc - std::panicking::try::h55d8916b3f7a3515\n  13:        0x103e44e52 - std::panic::catch_unwind::hf1717d8b89ed66e7\n  14:        0x103e46ffc - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hd9c5bf9811bb3b73\n  15:        0x103ea1a4c - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h0c4aa35835be38e8\n  16:        0x104471714 - std::sys::imp::thread::Thread::new::thread_start::hae18fa578e305215\n  17:     0x7fffb9b5693a - _pthread_body\n  18:     0x7fffb9b56886 - _pthread_start"}}, :path "session/", :payload nil, :method :delete, :type :etaoin/http-error, :port 4444, :host "127.0.0.1", :status 404, :driver {:args ["geckodriver" "--port" 4444], :desired-capabilities nil, :process #object[java.lang.UNIXProcess 0x5b2ade46 "java.lang.UNIXProcess@5b2ade46"], :locator "xpath", :type :firefox, :env {}, :port 4444, :host "127.0.0.1", :url "http://127.0.0.1:4444", :session nil}} {:response {:value {:error "unknown command", :message "DELETE /session/ did not match a known command", :stacktrace "stack backtrace:\n   0:        0x103fe3444 - backtrace::backtrace::trace::h9f8fad52a1a8acf1\n   1:        0x103fe37fe - backtrace::capture::Backtrace::new::hbc1a12654c8fdba8\n   2:        0x103f0df4d - webdriver::error::WebDriverError::new::h10bc8992bd1e5ce5\n   3:        0x103eb690d - _$LT$webdriver..httpapi..WebDriverHttpApi$LT$U$GT$$GT$::decode_request::h59625e2271927f5c\n   4:        0x103ef545e - _$LT$webdriver..server..HttpHandler$LT$U$GT$$u20$as$u20$hyper..server..Handler$GT$::handle::h75bcf4a70da4d3d8\n   5:        0x103e35b11 - _$LT$hyper..server..Worker$LT$H$GT$$GT$::keep_alive_loop::h6cffe26f2f997d81\n   6:        0x103e36665 - _$LT$hyper..server..Worker$LT$H$GT$$GT$::handle_connection::ha65f143767ef2701\n   7:        0x103ec24c1 - hyper::server::handle::_$u7b$$u7b$closure$u7d$$u7d$::h021c4837b0330036\n   8:        0x103ec2a5e - hyper::server::listener::spawn_with::_$u7b$$u7b$closure$u7d$$u7d$::h922fff03b485de70\n   9:        0x103f030a7 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hb095877d82356444\n  10:        0x103e47c86 - std::panicking::try::do_call::h7a395bca958e623c\n  11:        0x10447554a - __rust_maybe_catch_panic\n  12:        0x103e475bc - std::panicking::try::h55d8916b3f7a3515\n  13:        0x103e44e52 - std::panic::catch_unwind::hf1717d8b89ed66e7\n  14:        0x103e46ffc - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hd9c5bf9811bb3b73\n  15:        0x103ea1a4c - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h0c4aa35835be38e8\n  16:        0x104471714 - std::sys::imp::thread::Thread::new::thread_start::hae18fa578e305215\n  17:     0x7fffb9b5693a - _pthread_body\n  18:     0x7fffb9b56886 - _pthread_start"}}, :path "session/", :payload nil, :method :delete, :type :etaoin/http-error, :port 4444, :host "127.0.0.1", :status 404, :driver {:args ["geckodriver" "--port" 4444], :desired-capabilities nil, :process #object[java.lang.UNIXProcess 0x5b2ade46 "java.lang.UNIXProcess@5b2ade46"], :locator "xpath", :type :firefox, :env {}, :port 4444, :host "127.0.0.1", :url "http://127.0.0.1:4444", :session nil}}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at etaoin.client$call.invokeStatic(client.clj:97)
	at etaoin.client$call.invoke(client.clj:64)
	at etaoin.api$delete_session.invokeStatic(api.clj:150)
	at etaoin.api$delete_session.invoke(api.clj:148)
	at etaoin.api$disconnect_driver.invokeStatic(api.clj:1954)
	at etaoin.api$disconnect_driver.invoke(api.clj:1948)
	at etaoin.api$quit.invokeStatic(api.clj:1988)
	at etaoin.api$quit.invoke(api.clj:1984)
	at etaoin.api_test$fixture_browsers$fn__7159.invoke(api_test.clj:26)
	at etaoin.api_test$fixture_browsers.invokeStatic(api_test.clj:26)
	at etaoin.api_test$fixture_browsers.invoke(api_test.clj:23)
	at clojure.test$compose_fixtures$fn__7977$fn__7978.invoke(test.clj:693)
	at clojure.test$default_fixture.invokeStatic(test.clj:686)
	at clojure.test$default_fixture.invoke(test.clj:682)
	at clojure.test$compose_fixtures$fn__7977.invoke(test.clj:693)
	at clojure.test$test_vars$fn__8005.invoke(test.clj:734)
	at clojure.test$default_fixture.invokeStatic(test.clj:686)
	at clojure.test$default_fixture.invoke(test.clj:682)
	at clojure.test$test_vars.invokeStatic(test.clj:730)
	at clojure.test$test_all_vars.invokeStatic(test.clj:736)
	at clojure.test$test_ns.invokeStatic(test.clj:757)
	at clojure.test$test_ns.invoke(test.clj:742)
	at clojure.core$map$fn__4785.invoke(core.clj:2646)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1749)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.test$run_tests.invokeStatic(test.clj:767)
	at clojure.test$run_tests.doInvoke(test.clj:767)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at user$eval3200$fn__3263$fn__3294.invoke(form-init1325635718044467402.clj:1)
	at user$eval3200$fn__3263$fn__3264.invoke(form-init1325635718044467402.clj:1)
	at user$eval3200$fn__3263.invoke(form-init1325635718044467402.clj:1)
	at user$eval3200.invokeStatic(form-init1325635718044467402.clj:1)
	at user$eval3200.invoke(form-init1325635718044467402.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Tests failed.
```

**Comment by agodde** [comment]
I experience the same issue.

OS: Linux Mint 18 64Bit
Firefox version: 54
geckodriver: 0.18.0

**Comment by igrishaev** [comment]
yes, some tests fail, trying to fix them...

**Comment by agodde** [comment]
Unfortunately, it's not just "some tests" for me. I can create a firefox-driver (etaoin.api/firefox), but sending commands to the instance fails in any case. I presume it has something to do with the driver not containing a valid session id after creation (the key :session is always nil).

**Comment by olimsaidov** [comment]
This is because gecko-driver's `create session` response looks like:
```
{:value {:sessionId "2904896d-31a8-234d-8973-cc8d8064fed1",
         :capabilities {:moz:processID 16202,
                        :browserName "firefox",
                        :moz:profile "/var/folders/1l/8wxrg41n31v21xjft06mz5_w0000gn/T/rust_mozprofile.mCZPoHouiBy2",
                        :platformVersion "16.6.0",
                        :acceptInsecureCerts false,
                        :specificationLevel 0,
                        :pageLoadStrategy "normal",
                        :moz:accessibilityChecks false,
                        :browserVersion "54.0.1",
                        :rotatable false,
                        :timeouts {:implicit 0, :pageLoad 300000, :script 30000},
                        :platformName "darwin"}}}
```
not like as chrome-driver:
```
{:sessionId "3c380f7f40306c51ed6c0345255d1a73",
 :status 0,
 :value {:hasTouchScreen false,
         :browserName "chrome",
         :networkConnectionEnabled false,
         :acceptSslCerts true,
         :webStorageEnabled true,
         :mobileEmulationEnabled false,
         :pageLoadStrategy "normal",
         :applicationCacheEnabled false,
         :cssSelectorsEnabled true,
         :takesHeapSnapshot true,
         :setWindowRect true,
         :unexpectedAlertBehaviour "",
         :takesScreenshot true,
         :locationContextEnabled true,
         :handlesAlerts true,
         :chrome {:chromedriverVersion "2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b)",
                  :userDataDir "/var/folders/1l/8wxrg41n31v21xjft06mz5_w0000gn/T/.org.chromium.Chromium.ev2mkX"},
         :rotatable false,
         :browserConnectionEnabled false,
         :javascriptEnabled true,
         :version "60.0.3112.90",
         :nativeEvents true,
         :platform "Mac OS X",
         :databaseEnabled false}}
```

**Comment by olimsaidov** [comment]
As noted in gecko-driver release [v0.15.0](https://github.com/mozilla/geckodriver/releases/tag/v0.15.0):
> All HTTP responses are now wrapped in `{value: …}` objects per the WebDriver specification; this may likely require you to update your client library

**Comment by igrishaev** [comment]
Tests work finally with docker: 

```
make docker-build
make docker-test
```
